### ISSUE TITLE
Lesson Checklist

### ISSUE THREAD

**Issue by JakeWarren2414** [JakeWarren2414/FirstFastpages#13]
- [x] I will do 3.7 
- [ ] I will make sure to plan out how I am going to teach the students
- [ ] I will put the lesson into simple terms
- [ ] I will make sure to be engaging
- [x] I will create a scrum board
- [ ] I will use binary in my project
